spring.application.name=OrderManagement

spring.profiles.active=prod



#server.port=8001
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/flmfoods_services
#spring.datasource.username=root
#spring.datasource.password=

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


#eureka discovery client configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Config with config server
spring.config.import=optional:configserver:http://localhost:8888

#Actuator configurations
#management.endpoints.web.exposure.include=refresh
management.endpoints.web.exposure.include=*



# circuit Breaker Configurations
resilience4j.circuitbreaker.instances.orderManagementCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.orderManagementCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.orderManagementCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.orderManagementCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.orderManagementCB.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.orderManagementCB.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.orderManagementCB.minimum-number-of-calls=3





